[package]
name = "isuuc"
version = "0.1.0"
authors = ["Valerian <dogecoin.fraud@gmail.com>, Juan, Alexis"]

[dependencies]
ggez = "0.4"
tiled = "0.7.2"
rand = "0.5.4"
bincode = "1.0.1"
serde_derive = "1.0.70"
serde = "1.0.70"